#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-cucumber
Version  : 2.0.0
Release  : 6
URL      : https://rubygems.org/downloads/cucumber-2.0.0.gem
Source0  : https://rubygems.org/downloads/cucumber-2.0.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-cucumber-bin
BuildRequires : ruby
BuildRequires : rubygem-builder
BuildRequires : rubygem-bundler
BuildRequires : rubygem-capybara
BuildRequires : rubygem-cucumber-core
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-multi_test
BuildRequires : rubygem-pry
BuildRequires : rubygem-rack-test
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-simplecov
BuildRequires : rubygem-sinatra
BuildRequires : rubygem-syntax

%description
[![Build Status](https://secure.travis-ci.org/cucumber/cucumber.png)](http://travis-ci.org/cucumber/cucumber) [![Code Climate](https://codeclimate.com/github/cucumber/cucumber.png)](https://codeclimate.com/github/cucumber/cucumber) [![Coverage Status](https://coveralls.io/repos/cucumber/cucumber/badge.png?branch=master)](https://coveralls.io/r/cucumber/cucumber?branch=master) [![Dependency Status](https://gemnasium.com/cucumber/cucumber.png)](https://gemnasium.com/cucumber/cucumber)

%package bin
Summary: bin components for the rubygem-cucumber package.
Group: Binaries

%description bin
bin components for the rubygem-cucumber package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n cucumber-2.0.0
gem spec %{SOURCE0} -l --ruby > rubygem-cucumber.gemspec

%build
gem build rubygem-cucumber.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
cucumber-2.0.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/cucumber-2.0.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/.coveralls.yml
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/.rspec
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/.ruby-gemset
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/History.md
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/bin/cucumber
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/cucumber.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/cucumber.yml
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/README.textile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ar/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ar/features/addition.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ar/features/step_definitions/calculator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ar/lib/calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/bg/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/bg/features/addition.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/bg/features/consecutive_calculations.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/bg/features/division.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/bg/features/step_definitions/calculator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/bg/features/support/env.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/bg/features/support/world.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/bg/lib/calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ca/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ca/features/step_definitions/calculator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ca/features/suma.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ca/lib/calculadora.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/cs/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/cs/features/addition.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/cs/features/division.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/cs/features/step_definitions/calculator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/cs/lib/calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/da/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/da/features/sammenlaegning.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/da/features/step_definitions/lommeregner_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/da/lib/lommeregner.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/de/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/de/features/addition.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/de/features/division.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/de/features/step_definitions/calculator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/de/lib/calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/el/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/el/features/addition.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/el/features/division.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/el/features/step_definitions/calculator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/el/lib/calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/en-lol/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/en-lol/features/step_definitions/cucumbrz_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/en-lol/features/stuffing.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/en-lol/features/support/env.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/en-lol/lib/basket.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/en-lol/lib/belly.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/en/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/en/features/addition.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/en/features/division.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/en/features/step_definitions/calculator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/en/lib/calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/eo/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/eo/features/adicio.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/eo/features/divido.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/eo/features/step_definitions/calculator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/eo/lib/calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/es/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/es/features/adicion.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/es/features/step_definitions/calculador_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/es/lib/calculador.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/et/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/et/features/jagamine.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/et/features/liitmine.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/et/features/step_definitions/kalkulaator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/et/lib/kalkulaator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/fi/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/fi/features/jakolasku.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/fi/features/step_definitions/laskin_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/fi/features/yhteenlasku.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/fi/lib/laskin.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/fr/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/fr/features/addition.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/fr/features/addition2.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/fr/features/step_definitions/calculatrice_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/fr/features/support/env.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/fr/lib/calculatrice.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/he/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/he/features/addition.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/he/features/division.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/he/features/step_definitions/calculator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/he/lib/calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/hi/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/hi/features/addition.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/hi/features/division.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/hi/features/step_definitions/calculator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/hi/lib/calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ht/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ht/features/adisyon.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ht/features/divizyon.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ht/features/step_definitions/kalkilatris_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ht/lib/kalkilatris.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/hu/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/hu/features/osszeadas.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/hu/features/osztas.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/hu/features/step_definitions/calculator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/hu/lib/calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/id/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/id/features/addition.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/id/features/division.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/id/features/step_definitions/calculator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/id/lib/calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/it/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/it/features/somma.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/it/features/step_definitions/calcolatrice_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/it/lib/calcolatrice.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ja/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ja/features/addition.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ja/features/division.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ja/features/step_definitions/calculator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ja/features/support/env.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ja/lib/calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ko/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ko/features/addition.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ko/features/division.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ko/features/step_definitions/calculator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ko/lib/calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/lt/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/lt/features/addition.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/lt/features/division.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/lt/features/step_definitions/calculator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/lt/lib/calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/lv/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/lv/features/addition.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/lv/features/division.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/lv/features/step_definitions/calculator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/lv/lib/calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/no/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/no/features/step_definitions/kalkulator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/no/features/summering.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/no/features/support/env.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/no/lib/kalkulator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/pl/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/pl/features/addition.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/pl/features/division.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/pl/features/step_definitions/calculator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/pl/features/support/env.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/pl/lib/calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/pt/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/pt/features/adicao.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/pt/features/step_definitions/calculadora_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/pt/features/support/env.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/pt/lib/calculadora.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ro/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ro/features/adunare.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ro/features/step_definitions/calculator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ro/lib/calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ru/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ru/features/addition.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ru/features/consecutive_calculations.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ru/features/division.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ru/features/step_definitions/calculator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ru/features/support/env.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ru/features/support/world.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/ru/lib/calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/sk/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/sk/features/addition.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/sk/features/division.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/sk/features/step_definitions/calculator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/sk/lib/calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/sr-Cyrl/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/sr-Cyrl/features/sabiranje.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/sr-Cyrl/features/step_definitions/calculator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/sr-Cyrl/features/support/env.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/sr-Cyrl/lib/calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/sr-Latn/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/sr-Latn/features/sabiranje.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/sr-Latn/features/step_definitions/calculator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/sr-Latn/lib/calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/sv/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/sv/features/step_definitions/kalkulator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/sv/features/summering.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/sv/lib/kalkulator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/tr/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/tr/features/bolme.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/tr/features/step_definitions/hesap_makinesi_adimlari.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/tr/features/toplama.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/tr/lib/hesap_makinesi.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/uk/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/uk/features/addition.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/uk/features/consecutive_calculations.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/uk/features/division.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/uk/features/step_definitions/calculator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/uk/features/support/env.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/uk/features/support/world.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/uk/lib/calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/uz/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/uz/features/addition.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/uz/features/consecutive_calculations.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/uz/features/division.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/uz/features/step_definitions/calculator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/uz/features/support/env.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/uz/features/support/world.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/uz/lib/calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/zh-CN/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/zh-CN/features/addition.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/zh-CN/features/step_definitions/calculator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/zh-CN/lib/calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/zh-TW/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/zh-TW/features/addition.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/zh-TW/features/division.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/zh-TW/features/step_definitions/calculator_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/i18n/zh-TW/lib/calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/rspec_doubles/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/rspec_doubles/features/mocking.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/rspec_doubles/features/step_definitions/calvin_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/rspec_doubles/features/support/env.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/sinatra/README.textile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/sinatra/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/sinatra/app.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/sinatra/features/add.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/sinatra/features/step_definitions/add_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/sinatra/features/support/env.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/sinatra/views/add.erb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/sinatra/views/layout.erb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/tcl/README.textile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/tcl/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/tcl/features/fibonnacci.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/tcl/features/step_definitions/fib_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/tcl/features/support/env.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/tcl/src/fib.tcl
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/test_unit/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/test_unit/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/test_unit/features/step_definitions/test_unit_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/test_unit/features/test_unit.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/watir/README.textile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/watir/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/watir/cucumber.yml
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/watir/features/search.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/watir/features/step_definitions/search_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/watir/features/support/env.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/examples/watir/features/support/screenshots.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/api/list_step_defs_as_json.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/api/run_cli_main_with_existing_runtime.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/cli/backtraces.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/cli/dry_run.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/cli/exclude_files.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/cli/execute_with_tag_filter.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/cli/randomize.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/cli/require.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/cli/run_scenarios_matching_name.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/cli/run_specific_scenarios.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/cli/showing_differences.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/cli/specifying_multiple_formatters.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/cli/strict_mode.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/defining_steps/nested_steps.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/defining_steps/nested_steps_i18n.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/defining_steps/nested_steps_with_second_arg.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/defining_steps/one_line_step_definitions.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/defining_steps/printing_messages.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/defining_steps/skip_scenario.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/defining_steps/snippets.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/defining_steps/table_diffing.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/defining_steps/transforms.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/exception_in_after_hook.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/exception_in_after_step_hook.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/exception_in_around_hook.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/exception_in_before_hook.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/extending_cucumber/custom_filter.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/extending_cucumber/custom_formatter.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/formatters/debug_formatter.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/formatters/formatter_step_file_colon_line.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/formatters/html_formatter.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/formatters/json_formatter.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/formatters/junit_formatter.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/formatters/pretty_formatter.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/formatters/progress_formatter.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/formatters/rerun_formatter.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/formatters/usage_formatter.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/getting_started.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/gherkin/background.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/gherkin/doc_strings.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/gherkin/expand_option_for_outlines.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/gherkin/language_from_header.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/gherkin/language_help.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/gherkin/outlines.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/gherkin/unicode_table.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/gherkin/using_descriptions.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/gherkin/using_star_notation.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/iso-8859-1.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/post_configuration_hook.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/profiles.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/rake_task.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/raketask.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/wire_protocol/erb_configuration.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/wire_protocol/handle_unexpected_response.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/wire_protocol/invoke_message.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/wire_protocol/readme.md
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/wire_protocol/snippets_message.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/wire_protocol/step_matches_message.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/wire_protocol/table_diffing.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/wire_protocol/tags.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/wire_protocol/timeouts.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/work_in_progress.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/writing_support_code/after_hooks.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/writing_support_code/around_hooks.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/writing_support_code/before_hook.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/writing_support_code/hook_order.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/writing_support_code/load_path.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/writing_support_code/state.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/docs/writing_support_code/tagged_hooks.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/lib/step_definitions/aruba_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/lib/step_definitions/cucumber_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/lib/step_definitions/iso-8859-1_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/lib/step_definitions/json_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/lib/step_definitions/junit_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/lib/step_definitions/language_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/lib/step_definitions/profile_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/lib/step_definitions/ruby_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/lib/step_definitions/wire_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/lib/support/env.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/lib/support/fake_wire_server.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/lib/support/feature_factory.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/features/lib/support/normalise_output.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/gem_tasks/contributors.rake
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/gem_tasks/cov.rake
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/gem_tasks/cucumber.rake
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/gem_tasks/downloads.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/gem_tasks/environment.rake
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/gem_tasks/examples.rake
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/gem_tasks/fix_cr_lf.rake
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/gem_tasks/flog.rake
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/gem_tasks/rspec.rake
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/gem_tasks/sass.rake
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/gem_tasks/stats
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/gem_tasks/versions.txt
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/autotest/cucumber.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/autotest/cucumber_mixin.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/autotest/cucumber_rails.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/autotest/cucumber_rails_rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/autotest/cucumber_rails_rspec2.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/autotest/cucumber_rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/autotest/cucumber_rspec2.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/autotest/discover.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/ast.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/cli/configuration.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/cli/main.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/cli/options.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/cli/profile_loader.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/configuration.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/constantize.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/core_ext/instance_exec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/core_ext/proc.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/core_ext/string.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/encoding.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/errors.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/file_specs.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/filters.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/filters/activate_steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/filters/apply_after_hooks.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/filters/apply_after_step_hooks.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/filters/apply_around_hooks.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/filters/apply_before_hooks.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/filters/gated_receiver.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/filters/prepare_world.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/filters/quit.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/filters/randomizer.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/filters/tag_limits.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/filters/tag_limits/test_case_index.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/filters/tag_limits/verifier.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/ansicolor.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/console.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/cucumber.css
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/cucumber.sass
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/debug.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/duration.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/fanout.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/gherkin_formatter_adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/gpretty.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/html.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/ignore_missing_messages.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/interceptor.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/io.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/jquery-min.js
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/json.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/json_pretty.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/junit.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/legacy_api/adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/legacy_api/ast.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/legacy_api/results.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/legacy_api/runtime_facade.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/pretty.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/progress.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/rerun.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/stepdefs.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/steps.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/summary.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/unicode.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/formatter/usage.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/hooks.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/language_support.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/language_support/language_methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/load_path.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/multiline_argument.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/multiline_argument/data_table.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/multiline_argument/doc_string.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/platform.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/project_initializer.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/rake/task.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/rb_support/rb_dsl.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/rb_support/rb_hook.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/rb_support/rb_language.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/rb_support/rb_step_definition.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/rb_support/rb_transform.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/rb_support/rb_world.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/rb_support/regexp_argument_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/rb_support/snippet.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/rspec/disable_option_parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/rspec/doubles.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/running_test_case.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/runtime.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/runtime/after_hooks.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/runtime/before_hooks.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/runtime/for_programming_languages.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/runtime/step_hooks.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/runtime/support_code.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/runtime/user_interface.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/step_definition_light.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/step_definitions.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/step_match.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/term/ansicolor.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/unit.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/wire_support/configuration.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/wire_support/connection.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/wire_support/request_handler.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/wire_support/wire_exception.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/wire_support/wire_language.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/wire_support/wire_packet.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/wire_support/wire_protocol.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/wire_support/wire_protocol/requests.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/lib/cucumber/wire_support/wire_step_definition.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/cli/configuration_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/cli/main_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/cli/options_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/cli/profile_loader_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/configuration_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/constantize_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/core_ext/instance_exec_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/core_ext/proc_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/file_specs_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/filters/activate_steps_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/filters/gated_receiver_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/filters/tag_limits/test_case_index_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/filters/tag_limits/verifier_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/filters/tag_limits_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/formatter/ansicolor_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/formatter/debug_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/formatter/duration_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/formatter/html_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/formatter/interceptor_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/formatter/junit_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/formatter/legacy_api/adapter_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/formatter/pretty_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/formatter/progress_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/formatter/rerun_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/formatter/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/hooks_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/multiline_argument/data_table_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/project_initializer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/rake/forked_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/rb_support/rb_language_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/rb_support/rb_step_definition_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/rb_support/rb_transform_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/rb_support/regexp_argument_matcher_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/rb_support/snippet_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/running_test_case_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/runtime/for_programming_languages_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/runtime/support_code_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/runtime_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/sell_cucumbers.feature
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/step_match_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/wire_support/configuration_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/wire_support/connection_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/wire_support/wire_exception_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/wire_support/wire_language_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/wire_support/wire_packet_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/cucumber/world/pending_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/simplecov_setup.rb
/usr/lib64/ruby/gems/2.3.0/gems/cucumber-2.0.0/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/specifications/cucumber-2.0.0.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/cucumber
